### ISSUE TITLE
format the git tag annotation data better

### ISSUE THREAD

**Issue by willkg** [willkg/socorro-release#36]
Currently, the release script creates a git tag annotation, but it's rendered poorly on GitHub.

For example:

https://github.com/mozilla-services/socorro/releases/tag/2023.10.04

That should be valid markdown. Why doesn't it get rendered as markdown?

This covers figuring out how to make that render better with commit links and bug links and such.

**Comment by willkg** [comment]
It might be because GitHub treats that field as plain text and there's no way to tell it to do otherwise.

But we could create _releases_ using the `gh` tool and in doing that specify that the blob is markdown and then it'd show up as markdown on the releases page.

https://github.com/orgs/community/discussions/22611

**Comment by biancadanforth** [comment]
I tried using GitHub's [autolinking for external resources](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-autolinks-to-reference-external-resources) which FxA uses, but unfortunately, they don't allow spaces in the reference prefix (see attached screenshot).

![Screenshot 2023-10-19 at 4 32 32 PM](https://github.com/willkg/socorro-release/assets/17437436/da6b60c3-74e8-4f11-925f-ce6dabf734ff)

However, if we update `rob-bugson` to accept `-` instead of a space, e.g. `bug-12345`, then we could try that route (and I think it'd work, since it works for git commit messages per this [example](https://github.com/mozilla/fxa/pull/15870)).

![Screenshot 2023-10-19 at 4 37 28 PM](https://github.com/willkg/socorro-release/assets/17437436/9774ebef-5465-459a-b042-b6923ba2bf8e)
